version: '2.0'
services:
  fowrarding-nginx:
    container_name: nginx
    image: nginx
    ports:
      - '0.0.0.0:80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites/:/etc/nginx/sites/:ro
      - ./build/:/usr/share/nginx/html/:ro
    restart: always
